### ISSUE TITLE
Add steps to run this project

### ISSUE THREAD

**Issue by Nit89** [Nit89/PARKINSON-S-DISEASE-PREDICTION#5]

**Comment by rehan985** [comment]
Hi, Do You want a complete guide on how to execute this project completely?

**Comment by Nit89** [comment]
yes, a more detailed guide will be more useful. Also, we just started pushing code, so a basic one will be good

**Comment by rehan985** [comment]
ok sure, I am working on it and will share the guide soon.

**Comment by Nit89** [comment]
> ok sure, I am working on it and will share the guide soon.

sure

**Comment by Nit89** [comment]
hey, this is a Django project  could you also able to write the  steps that involve how to run Django project
